### ISSUE TITLE
Other software packages or any specifications as children of Riffol the open project?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/riffol.github.io#5]
@ronaldtse, @drystone — would you say Riffol in foreseeable future will consist of just one software package and nothing else?

**Comment by drystone** [comment]
@strogonoff Riffol is standalone. It depends on [libucl](https://github.com/vstakhov/libucl) and `pidof` (a dependency I'd hope to remove) which may need to be installed separately.

**Comment by strogonoff** [comment]
Got it.

I was more about e.g. acquiring a Go implementation, or adding an interoperable piece of Rust software, i.e. adding to to Riffol family, not so much dependencies (and libucl seems to be not developed by Ribose so it’s out)

**Comment by ronaldtse** [comment]
Sorry I missed this one. Riffol itself is standalone, but can be used in conjunction with Nereond (https://github.com/riboseinc/nereond), and in the future, probably also other components.

We will seek replacement of libucl once we have a stable Nereon syntax (https://github.com/riboseinc/nereon-syntax), but it's quite a bit of work for now.

**Comment by strogonoff** [comment]
@ronaldtse Got it, they’re two separate projects for now.

I’m feeling the theme will have to provide a simplified navigation for an open project with single software package and no specs, sounds like a very typical use case

**Comment by ronaldtse** [comment]
Yes indeed, thanks!

**Comment by strogonoff** [comment]
(Filed https://github.com/riboseinc/jekyll-theme-open-project/issues/33 for that feature)
